module.exports = {
	_classes : {

		// community - Feb 6 2012
		"a-download"                         : "download",
		"audio-audiodata-api"                : "audiodata",
		"audio-webaudio-api"                 : "webaudio",
		"battery-api"                        : "battery",
		"battery-level"                      : "lowbattery",
		"canvas-todataurl-type"              : ["todataurljpeg", "todataurlwebp"],
		"contenteditable"                    : "contenteditable",
		"contextmenu"                        : "contextmenu",
		"cookies"                            : "cookies",
		"cors"                               : "cors",
		"css-backgroundrepeat"               : ["bgrepeatround", "bgrepeatspace"],
		"css-backgroundsizecover"            : "bgsizecover",
		"css-boxsizing"                      : "boxsizing",
		"css-cubicbezierrange"               : "cubicbezierrange",
		"css-displayrunin"                   : "display-runin",
		"css-displaytable"                   : "display-table",
		"css-hyphens"                        : ["csshyphens", "softhyphens", "softhyphensfind"],
		"css-mask"                           : "cssmask",
		"css-mediaqueries"                   : "mediaqueries",
		"css-overflow-scrolling"             : "overflowscrolling",
		"css-pointerevents"                  : "pointerevents",
		"css-remunit"                        : "cssremunit",
		"css-resize"                         : "cssresize",
		"css-scrollbars"                     : "cssscrollbar",
		"css-userselect"                     : "userselect",
		"custom-protocol-handler"            : "customprotocolhandler",
		"dataview-api"                       : "dataview",
		"dom-classlist"                      : "classlist",
		"createelement-attrs"                : "dom-createElement-attrs",
		"dom-dataset"                        : "dataset",
		"dom-microdata"                      : "microdata",
		"elem-datalist"                      : "datalistelem",
		"elem-details"                       : "details",
		"elem-output"                        : "outputelem",
		"elem-progress-meter"                : ["progressbar", "meter"],
		"elem-ruby"                          : "ruby",
		"elem-time"                          : "time",
		"elem-track"                         : ["texttrackapi", "track"],
		"emoji"                              : "emoji",
		"strictmode"                         : "es5-strictmode",
		"event_deviceorientation_motion"     : ["devicemotion", "deviceorientation", "exif-orientation"],
		"file-api"                           : "filereader",
		"file-filesystem"                    : "filesystem",
		"forms-placeholder"                  : "placeholder",
		"forms-speechinput"                  : "speechinput",
		"forms-validation"                   : "formvalidation",
		"fullscreen-api"                     : "fullscreen",
		"gamepad"                            : "gamepads",
		"getusermedia"                       : "getusermedia",
		"ie8compat"                          : "ie8compat",
		"img-apng"                           : "apng",
		"img-webp"                           : "webp",
		"json"                               : "json",
		"lists-reversed"                     : "olreversed",
		"mathml"                             : "mathml",
		"network-connection"                 : "lowbandwidth",
		"network-eventsource"                : "eventsource",
		"notification"                       : "notification",
		"performance"                        : "performance",
		"quota-management-api"               : "quotamanagement",
		"requestanimationframe"              : "raf",
		"script-async"                       : "scriptasync",
		"script-defer"                       : "scriptdefer",
		"unicode"                            : "unicode",
		"url-data-uri"                       : "datauri",
		"userdata"                           : "userdata",
		"web-intents"                        : "webintents",
		"websockets-binary"                  : "websocketsbinary",
		"window-framed"                      : "framed",
		"workers-blobworkers"                : "blobworkers",
		"workers-dataworkers"                : "dataworkers",
		"workers-sharedworkers"              : "sharedworkers",

		/* added  july 16 2012 */
		"blob-constructor"                   : "blobconstructor",
		"css-backgroundposition-xy"          : "bgpositionxy",
		"css-calc"                           : "csscalc",
		"css-lastchild"                      : "lastchild",
		"css-regions"                        : "regions",
		"css-subpixelfont"                   : "subpixelfont",
		"xhr2"                               : "network-xhr2",
		"style-scoped"                       : "stylescoped",
		"svg-filters"                        : "svgfilters",
		"forms-fileinput"                    : "fileinput",
		"vibration"                          : "vibrate",

		/* added sept 3rd */
		"contentsecuritypolicy"              : "contentsecuritypolicy",
		"css-objectfit"                      : "object-fit",
		"css-positionsticky"                 : "csspositionsticky",
		"css-supports"                       : "supports",
		"css-vhunit"                         : "cssvhunit",
		"css-vmaxunit"                       : "cssvmaxunit",
		"css-vminunit"                       : "cssvminunit",
		"css-vwunit"                         : "cssvwunit",
		"forms-formattribute"                : "formattribute",
		"iframe-sandbox"                     : "sandbox",
		"iframe-seamless"                    : "seamless",
		"iframe-srcdoc"                      : "srcdoc",
		"pointerlock-api"                    : "pointerlock"

		// 404s
		// bgpositionshorthand
		// css_backgroundcliptext
		// cssfilters
		// vibration
	}
};
